### ISSUE TITLE
PhpStorm 10 IndexOutOfBoundsException: Index out of range

### ISSUE THREAD

**Issue by 4levels** [edwtjo/nixitch#3]
I'm getting this error when opening a rather complex nix expression.  The file itself validates correctly when being used by NixOps..  This error prevents the file from being opened in PhpStorm, so I have no other option but to disable this plugin completely.

Please find the expression below.

```
{config, lib, pkgs, ...}:
let
  cfg = config.services.fusioninvoice;
  serviceDir = "/var/lib/fusioninvoice";
  systemdService = name: value:
    {
      name = "fusioninvoice-${name}";
      value = {
        description = "FusionInvoice ${name} service";
        wantedBy = [ "multi-user.target" "nginx.target" ];
        after = [ "network.target" "mysql.target" ];
        path = [ pkgs.curl pkgs.cacert ];
        environment = {
          inherit (config.environment.variables) SSL_CERT_FILE;
        };
      };
    };
  packageActivation = name: value:
    {
      name = "fusioninvoice-${name}";
      value = ''
        # create / symlink project dirs
        mkdir -p ${serviceDir}/${name}
        mkdir -p ${serviceDir}/${name}/web
        ln -sf   ${fusioninvoicePackage}/app ${serviceDir}/${name}/
        ln -sf   ${fusioninvoicePackage}/assets ${serviceDir}/${name}/
        cp -a    ${fusioninvoicePackage}/bootstrap ${serviceDir}/${name}/
        cp -a    ${fusioninvoicePackage}/config ${serviceDir}/${name}/
        cp -a    ${fusioninvoicePackage}/custom ${serviceDir}/${name}/
        ln -sf   ${fusioninvoicePackage}/database ${serviceDir}/${name}/
        ln -sf   ${fusioninvoicePackage}/resources ${serviceDir}/${name}/
        ln -sf   ${fusioninvoicePackage}/vendor ${serviceDir}/${name}/
        cp -a    ${fusioninvoicePackage}/storage ${serviceDir}/${name}/
        mkdir -p ${serviceDir}/${name}/log
        ln -sf   ${serviceDir}/${name}/assets ${serviceDir}/${name}/web/
        cp -a    ${fusioninvoicePackage}/{artisan,composer.json,composer.lock,LICENSE,package.json} ${serviceDir}/${name}/
        cp -a    ${fusioninvoicePackage}/{favicon.png,index.php,robots.txt} ${serviceDir}/${name}/web/
        # log files
        touch ${serviceDir}/${name}/log/{error.log,access.log}
        chown -R nginx ${serviceDir}/${name}/{log,storage}
        chmod -R u+w,g+w ${serviceDir}/${name}/{log,storage}
        chown -R nginx ${serviceDir}/${name}/bootstrap/cache
        chmod -R u+w,g+w ${serviceDir}/${name}/bootstrap/cache
        # Create database and user
        echo "CREATE DATABASE IF NOT EXISTS invoices_${name};" | ${pkgs.mysql}/bin/mysql -u root -N;
        echo "DROP USER 'inv_${name}'@'localhost';" | ${pkgs.mysql}/bin/mysql -u root -N;
        ( echo "CREATE USER 'inv_${name}'@'localhost' IDENTIFIED BY '${value.database.password}';"
          echo "GRANT ALL ON invoices_${name}.* TO 'inv_${name}'@'localhost';"
          echo "GRANT FILE ON *.* TO 'inv_${name}'@'localhost';"
          echo "FLUSH PRIVILEGES;" ) | ${pkgs.mysql}/bin/mysql -u root -N;
        # Update database config
        ${pkgs.replace}/bin/replace-literal -e fusioninvoice ${value.database.name} -a root ${value.database.username} -a "'password'," "'${value.database.password}'," ${serviceDir}/${name}/config/database.php
        # Updated fusioninvoice config
        ${pkgs.replace}/bin/replace-literal -e ReplaceThisWithYourOwnLicenseKey ${value.app.key} -a http://localhost https://${value.app.host} -a UTC ${value.app.timezone} ${serviceDir}/${name}/config/app.php
        # Updated fusioninvoice front controller with web path
        ${pkgs.replace}/bin/replace-literal -e "__DIR__.'/bootstrap" "__DIR__.'/../bootstrap" ${serviceDir}/${name}/web/index.php
      '';
    };
  fusioninvoicePackage = (import ./fusioninvoice-package.nix);
  phpFpmPoolConfig = builtins.readFile ./src/phpfpm-pool0.conf;
  sslCert = ./src/ssl-cert.pem;
  sslKey = ./src/ssl-key.pem;
  sslCA = ./src/ssl-ca.pem;
  sslDHParam = ./src/ssl-dhparam.pem;
  nginxVhostLocations = ''
    location ~ "^(.+\.php)($|/)" {
      include ${pkgs.nginx}/conf/mime.types;
      ${builtins.readFile ./src/nginx-php-config.conf}
    }
    location / {
      include ${pkgs.nginx}/conf/mime.types;
      ${builtins.readFile ./src/nginx-rewrite.conf}
    }
  '';
  nginxHttpBaseConfig = builtins.readFile ./src/nginx-http-base.conf;
  nginxSslConfig = ''
    ${builtins.readFile ./src/nginx-ssl.conf}
    ssl_certificate      ${sslCert};
    ssl_certificate_key  ${sslKey};
    ssl_trusted_certificate ${sslCA};
    ssl_dhparam ${sslDHParam};
  '';
  timers = platforms: {
    fusioninvoice-tasks = {
      description = "FusionInvoice task process service";
      after = [ "network.target" "mysql.target" ];
      environment = {
        inherit (config.environment.variables) SSL_CERT_FILE;
      };
      path = [ pkgs.curl ];
      script = lib.concatStrings (lib.mapAttrsToList (n: v:
        if lib.hasAttr("runTasks") v && v.runTasks == true then
          "\ncd ${serviceDir}/${n} && curl https://${v.app.host}/tasks/run"
        else ""
      ) platforms);
      startAt = "*-*-* 14:00:00";
    };
  };

in

with lib;
{
  options = {
    services.fusioninvoice = {
      platforms = mkOption {
        default = {};
        example = {
          test = {
            app = {};
            database = {
              password = "foopass";
            };
            runTasks = true;
          };
        };
      };
    };
  };

  config = mkIf (cfg.platforms != {}) {
    system.activationScripts = mapAttrs' packageActivation cfg.platforms;
    systemd.services = mapAttrs' systemdService cfg.platforms // timers cfg.platforms;
    services.phpfpm.poolConfigs = {
      pool0 = phpFpmPoolConfig;
    };
    services.nginx = {
      enable = true;
      httpConfig = ''
        ${concatStringsSep "\n" (mapAttrsToList (n: v: ''
          # redirect to SSL
          server {
            server_name ${v.app.host} www.${v.app.host};
            ssl off;
            return 301 https://${v.app.host}$request_uri;
          }
          # fusioninvoice project
          server {
            server_name ${v.app.host};
            ${nginxSslConfig}
            root ${serviceDir}/${n}/web;
            access_log ${serviceDir}/${n}/log/access.log combined;
            error_log ${serviceDir}/${n}/log/error.log;
            ${nginxVhostLocations}
          }
        '') cfg.platforms)}
      '';
    };
  };
}
```

This is the error message from PhpStorm

Index out of range: 9143
java.lang.IndexOutOfBoundsException: Index out of range: 9143
    at com.intellij.util.text.ImmutableText.charAt(ImmutableText.java:270)
    at com.intellij.util.text.CharSequenceSubSequence.charAt(CharSequenceSubSequence.java:50)
    at cc.cflags.nixitch.lang.NixLexer.advance(Unknown Source)
    at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:95)
    at com.intellij.lexer.FlexAdapter.getTokenType(FlexAdapter.java:58)
    at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.a(LexerEditorHighlighter.java:321)
    at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.setText(LexerEditorHighlighter.java:302)
    at com.intellij.openapi.editor.impl.EditorImpl.setHighlighter(EditorImpl.java:1182)
    at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.a(TextEditorComponent.java:168)
    at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.<init>(TextEditorComponent.java:100)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:62)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:55)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.createEditorComponent(PsiAwareTextEditorImpl.java:44)
    at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.<init>(TextEditorImpl.java:46)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.<init>(PsiAwareTextEditorImpl.java:38)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$1.build(PsiAwareTextEditorProvider.java:77)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$13.run(FileEditorManagerImpl.java:873)
    at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2382)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:855)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:789)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$10.run(FileEditorManagerImpl.java:769)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:766)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:707)
    at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:151)
    at com.intellij.codeInsight.navigation.NavigationUtil.a(NavigationUtil.java:200)
    at com.intellij.codeInsight.navigation.NavigationUtil.openFileWithPsiElement(NavigationUtil.java:176)
    at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:207)
    at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:217)
    at com.intellij.ide.projectView.impl.nodes.PsiFileNode.navigate(PsiFileNode.java:132)
    at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:53)
    at com.intellij.util.OpenSourceUtil.openSourcesFrom(OpenSourceUtil.java:31)
    at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.java:130)
    at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.java:122)
    at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
    at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:410)
    at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:58)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

java.lang.IndexOutOfBoundsException: Index out of range: 9143
    at com.intellij.util.text.ImmutableText.charAt(ImmutableText.java:270)
    at com.intellij.util.text.CharSequenceSubSequence.charAt(CharSequenceSubSequence.java:50)
    at cc.cflags.nixitch.lang.NixLexer.advance(Unknown Source)
    at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:95)
    at com.intellij.lexer.FlexAdapter.getTokenType(FlexAdapter.java:58)
    at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.a(LexerEditorHighlighter.java:321)
    at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.setText(LexerEditorHighlighter.java:302)
    at com.intellij.openapi.editor.impl.EditorImpl.setHighlighter(EditorImpl.java:1182)
    at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.a(TextEditorComponent.java:168)
    at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.<init>(TextEditorComponent.java:100)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:62)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:55)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.createEditorComponent(PsiAwareTextEditorImpl.java:44)
    at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.<init>(TextEditorImpl.java:46)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.<init>(PsiAwareTextEditorImpl.java:38)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$1.build(PsiAwareTextEditorProvider.java:77)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.createEditor(PsiAwareTextEditorProvider.java:49)
    at com.intellij.ide.impl.StructureViewWrapperImpl.a(StructureViewWrapperImpl.java:397)
    at com.intellij.ide.impl.StructureViewWrapperImpl.rebuild(StructureViewWrapperImpl.java:309)
    at com.intellij.ide.impl.StructureViewWrapperImpl$6.run(StructureViewWrapperImpl.java:253)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
    at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2361)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:283)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
    at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by edwtjo** [comment]
Ok, thank you for the report. I'll address this in the coming version of the plugin.
